#include<stdio.h>
int main()
{
    int arr2[3][3];
    int arr1[3][3] = {{1, 1, 1},{1, 1, 1},{1, 1, 1}};
    for(int i=0; i<3; i++)
    {
        for(int j=0; j<3; j++)
        {
            scanf("%d",&arr2[i][j]);
        }
    }
    for(int i=0; i<3; i++)
    {
        for(int j=0; j<3; j++)
        {
            if(arr2[i][j]>0)
            {
                for(int k=0; k<arr2[i][j]; k++)
                {
                    if(i==1 && j==1)
                    {
                        if(arr1[i][j]==0)
                        {
                            arr1[i][j]=1;
                        }
                        else
                        {
                            arr1[i][j]=0;
                        }
                        if(arr1[i-1][j]==0)
                        {
                            arr1[i-1][j]=1;
                        }
                        else
                        {
                            arr1[i-1][j]=0;
                        }
                        if(arr1[i+1][j]==0)
                        {
                            arr1[i+1][j]=1;
                        }
                        else
                        {
                            arr1[i+1][j]=0;
                        }
                        if(arr1[i][j+1]==0)
                        {
                            arr1[i][j+1]=1;
                        }
                        else
                        {
                            arr1[i][j+1]=0;
                        }
                        if(arr1[i][j-1]==0)
                        {
                            arr1[i][j-1]=1;
                        }
                        else
                        {
                            arr1[i][j-1]=0;
                        }
                    }
                    else if(i==0 && j==0)
                    {
                        if(arr1[i][j]==0)
                        {
                            arr1[i][j]=1;
                        }
                        else
                        {
                            arr1[i][j]=0;
                        }
                        if(arr1[i+1][j]==0)
                        {
                            arr1[i+1][j]=1;
                        }
                        else
                        {
                            arr1[i+1][j]=0;
                        }
                        if(arr1[i][j+1]==0)
                        {
                            arr1[i][j+1]=1;
                        }
                        else
                        {
                            arr1[i][j+1]=0;
                        }
                    }
                    else if(i==0 && j==2)
                    {
                        if(arr1[i][j]==0)
                        {
                            arr1[i][j]=1;
                        }
                        else
                        {
                            arr1[i][j]=0;
                        }
                        if(arr1[i+1][j]==0)
                        {
                            arr1[i+1][j]=1;
                        }
                        else
                        {
                            arr1[i+1][j]=0;
                        }
                        if(arr1[i][j-1]==0)
                        {
                            arr1[i][j-1]=1;
                        }
                        else
                        {
                            arr1[i][j-1]=0;
                        }
                    }
                    else if(i==2 && j==0)
                    {
                        if(arr1[i][j]==0)
                        {
                            arr1[i][j]=1;
                        }
                        else
                        {
                            arr1[i][j]=0;
                        }
                        if(arr1[i-1][j]==0)
                        {
                            arr1[i-1][j]=1;
                        }
                        else
                        {
                            arr1[i-1][j]=0;
                        }
                        if(arr1[i][j+1]==0)
                        {
                            arr1[i][j+1]=1;
                        }
                        else
                        {
                            arr1[i][j+1]=0;
                        }
                    }
                    else if(i==2 && j==2)
                    {
                        if(arr1[i][j]==0)
                        {
                            arr1[i][j]=1;
                        }
                        else
                        {
                            arr1[i][j]=0;
                        }
                        if(arr1[i-1][j]==0)
                        {
                            arr1[i-1][j]=1;
                        }
                        else
                        {
                            arr1[i-1][j]=0;
                        }
                        if(arr1[i][j-1]==0)
                        {
                            arr1[i][j-1]=1;
                        }
                        else
                        {
                            arr1[i][j-1]=0;
                        }
                    }
                    else if(i==0 && j==1)
                    {
                        if(arr1[i][j]==0)
                        {
                            arr1[i][j]=1;
                        }
                        else
                        {
                            arr1[i][j]=0;
                        }
                        if(arr1[i+1][j]==0)
                        {
                            arr1[i+1][j]=1;
                        }
                        else
                        {
                            arr1[i+1][j]=0;
                        }
                        if(arr1[i][j+1]==0)
                        {
                            arr1[i][j+1]=1;
                        }
                        else
                        {
                            arr1[i][j+1]=0;
                        }
                        if(arr1[i][j-1]==0)
                        {
                            arr1[i][j-1]=1;
                        }
                        else
                        {
                            arr1[i][j-1]=0;
                        }
                    }
                    else if(i==1 && j==0)
                    {
                        if(arr1[i][j]==0)
                        {
                            arr1[i][j]=1;
                        }
                        else
                        {
                            arr1[i][j]=0;
                        }
                        if(arr1[i+1][j]==0)
                        {
                            arr1[i+1][j]=1;
                        }
                        else
                        {
                            arr1[i+1][j]=0;
                        }
                        if(arr1[i][j+1]==0)
                        {
                            arr1[i][j+1]=1;
                        }
                        else
                        {
                            arr1[i][j+1]=0;
                        }
                        if(arr1[i-1][j]==0)
                        {
                            arr1[i-1][j]=1;
                        }
                        else
                        {
                            arr1[i-1][j]=0;
                        }
                    }
                    else if(i==2 && j==1)
                    {
                        if(arr1[i][j]==0)
                        {
                            arr1[i][j]=1;
                        }
                        else
                        {
                            arr1[i][j]=0;
                        }
                        if(arr1[i][j+1]==0)
                        {
                            arr1[i][j+1]=1;
                        }
                        else
                        {
                            arr1[i][j+1]=0;
                        }
                        if(arr1[i][j-1]==0)
                        {
                            arr1[i][j-1]=1;
                        }
                        else
                        {
                            arr1[i][j-1]=0;
                        }
                        if(arr1[i-1][j]==0)
                        {
                            arr1[i-1][j]=1;
                        }
                        else
                        {
                            arr1[i-1][j]=0;
                        }
                    }
                    else if(i==1 && j==2)
                    {
                        if(arr1[i][j]==0)
                        {
                            arr1[i][j]=1;
                        }
                        else
                        {
                            arr1[i][j]=0;
                        }
                        if(arr1[i+1][j]==0)
                        {
                            arr1[i+1][j]=1;
                        }
                        else
                        {
                            arr1[i+1][j]=0;
                        }
                        if(arr1[i][j-1]==0)
                        {
                            arr1[i][j-1]=1;
                        }
                        else
                        {
                            arr1[i][j-1]=0;
                        }
                        if(arr1[i-1][j]==0)
                        {
                            arr1[i-1][j]=1;
                        }
                        else
                        {
                            arr1[i-1][j]=0;
                        }
                    }
                }
            }
        }
    }
    for(int i=0; i<3; i++)
    {
        for(int j=0; j<3; j++)
        {
            printf("%d",arr1[i][j]);
        }
        printf("\n");
    }
    return 0;
}
